import streamlit as st
import pandas as pd
import time
from datetime import datetime
import os
import base64
import plotly.graph_objects as go

# --- SAFE FPDF IMPORT FOR REPORT GENERATION ---
try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False

# --- 1. UI CONFIGURATION & THEME ---
st.set_page_config(page_title="DAP-2026 Eligibility Simulator", page_icon="🏛️", layout="wide")

# Columns for Language Selection at the top right
col_hdr, col_lang = st.columns([5, 1.2])
with col_lang:
    selected_language = st.selectbox(
        "🌐 Language / भाषा चुनें",
        ["English", "हिन्दी (Hindi)"],
        index=0,
        help="Switch interface language / इंटरफ़ेस भाषा बदलें"
    )

is_hindi = (selected_language == "हिन्दी (Hindi)")

# Hardcoded Theme Variables for Light Mode Navy Default
theme_axis_color = "#31333F"
chart_theme = None
navy_blue = "#1E3A8A"  # Official Navy Accent
navy_hover = "#1E40AF"

# --- 2. TRANSLATION DICTIONARY (BILINGUAL ENGINE) ---
T = {
    "app_title": "DAP" if not is_hindi else "डैप",
    "app_subtitle": "DIPLOMA ADMISSION PROCESS • ELIGIBILITY SIMULATOR" if not is_hindi else "डिप्लोमा प्रवेश प्रक्रिया • पात्रता सिम्युलेटर",
    "disclaimer_title": "OFFICIAL DISCLAIMER:" if not is_hindi else "आधिकारिक अस्वीकरण (Disclaimer):",
    "disclaimer_text": (
        "This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers and "
        "effective scores generated by this tool are tentative and based entirely on the unverified data "
        "entered by the candidate. The final, official merit list will be generated by the Centre for Electronic Governance (CEG) "
        "during the actual DAP-2026 Centralized Admission Process."
    ) if not is_hindi else (
        "यह पात्रता सिम्युलेटर केवल सूचनात्मक और मार्गदर्शन उद्देश्यों के लिए प्रदान किया गया है। इस टूल द्वारा उत्पन्न अनुमानित प्राथमिकता "
        "स्तर और प्रभावी अंक पूरी तरह से अनंतिम (tentative) हैं। अंतिम, आधिकारिक योग्यता सूची वास्तविक DAP-2026 प्रवेश प्रक्रिया "
        "के दौरान मूल दस्तावेजों के गहन सत्यापन के बाद सेंटर फॉर इलेक्ट्रॉनिक गवर्नेंस (CEG) द्वारा ही जारी की जाएगी।"
    ),
    "eval_details_header": "📋 Candidate Evaluation Details" if not is_hindi else "📋 अभ्यर्थी मूल्यांकन विवरण",
    "step1_title": "🎓 Step 1: Academic & Admission Information" if not is_hindi else "🎓 चरण 1: शैक्षणिक और प्रवेश जानकारी",
    "cand_name": "Candidate Name" if not is_hindi else "अभ्यर्थी का नाम",
    "dob": "Date of Birth" if not is_hindi else "जन्म तिथि",
    "dob_help": "Used as the primary tie-breaker. Older candidates rank higher." if not is_hindi else "प्राथमिक टाई-ब्रेकर के रूप में उपयोग किया जाता है। अधिक आयु वाले अभ्यर्थी को उच्च रैंक मिलती है।",

    # DAP Specific Academic Strings
    "adm_type": "Admission Pathway" if not is_hindi else "प्रवेश का प्रकार",
    "qual_basis": "Qualifying Examination" if not is_hindi else "पात्रता परीक्षा",
    "perc_qual": "Qualifying Exam Overall (%)" if not is_hindi else "अर्हक परीक्षा कुल (%)",
    "cutoff_help": "Eligibility cutoff is typically 35%." if not is_hindi else "प्रवेश के लिए पात्रता कटऑफ 35% है।",

    "subject_12_title": "Select 12th Board Subjects (Lateral Entry)" if not is_hindi else "12वीं बोर्ड विषयों का चयन करें (लेटरल एंट्री)",
    "subject_12_caption": "Mandatory: Physics. Your subject combination determines which branches you are eligible for." if not is_hindi else "अनिवार्य: भौतिक विज्ञान। आपका विषय संयोजन यह निर्धारित करता है कि आप किन शाखाओं के लिए पात्र हैं।",
    "sub1_label": "Subject 1 (Locked)" if not is_hindi else "विषय 1 (लॉक)",
    "sub2_label": "Subject 2" if not is_hindi else "विषय 2",
    "sub3_label": "Subject 3" if not is_hindi else "विषय 3",

    # Demographics & Priority
    "step2_title": "🌍 Step 2: Priority 1 Eligibility & Category" if not is_hindi else "🌍 चरण 2: प्राथमिकता 1 पात्रता और श्रेणी",
    "gender": "Gender" if not is_hindi else "लिंग",
    "gender_help": "Female candidates receive horizontal reservations." if not is_hindi else "महिला अभ्यर्थियों को क्षैतिज आरक्षण प्राप्त होता है।",
    "base_cat": "Base Category" if not is_hindi else "मूल श्रेणी",
    "area": "Area Type" if not is_hindi else "क्षेत्र का प्रकार",
    "domicile": "1. Domicile State" if not is_hindi else "1. मूल निवास (Domicile)",
    "passed_raj": "2. Passed Qualifying Exam from a school in Rajasthan?" if not is_hindi else "2. क्या अर्हक परीक्षा राजस्थान के स्कूल से उत्तीर्ण की है?",
    "govt_emp": "3. Dependent of Govt. of Rajasthan Employee?" if not is_hindi else "3. क्या राजस्थान सरकार के कर्मचारी के आश्रित हैं?",
    "psu_emp": "4. Dependent of Board/PSU/Central Govt posted in Rajasthan?" if not is_hindi else "4. क्या बोर्ड/पीएसयू/केंद्र सरकार (राजस्थान में पदस्थापित) के आश्रित हैं?",
    "passed_bter": "5. Passed Diploma from Pravidhik Shiksha Mandal, Jodhpur?" if not is_hindi else "5. क्या प्राविधिक शिक्षा मंडल, जोधपुर से डिप्लोमा उत्तीर्ण किया है?",
    "passed_iti_raj": "6. Passed ITI from an institute in Rajasthan?" if not is_hindi else "6. क्या राजस्थान के संस्थान से ITI उत्तीर्ण किया है?",
    "priority_help": "Meeting ANY of the active conditions below grants Priority 1 status (State Merit Eligibility)." if not is_hindi else "नीचे दी गई किसी भी सक्रिय शर्त को पूरा करने पर प्राथमिकता 1 का दर्जा (राज्य मेरिट पात्रता) मिलता है।",

    # Quotas
    "step3_title": "⭐ Step 3: Quotas & Horizontal Reservations" if not is_hindi else "⭐ चरण 3: कोटा और क्षैतिज आरक्षण",
    "fn_label": "Foreign National / OCI / Gulf" if not is_hindi else "विदेशी नागरिक / OCI / खाड़ी देश कोटा",
    "fn_help": "15% supernumerary seats for Foreign Nationals/OCI. Removes candidate from main admission pool." if not is_hindi else "विदेशी नागरिकों/OCI के लिए 15% अतिरिक्त अधिसंख्य सीटें। मुख्य प्रवेश पूल से अलग करता है।",
    "pwd_label": "Person with Special Ability (PwD)" if not is_hindi else "विशेष योग्यजन (PwD)",
    "pwd_help": "Grants a 5% horizontal reservation." if not is_hindi else "5% क्षैतिज आरक्षण प्रदान करता है।",
    "tfws_label": "Income < ₹8.00 Lakhs (TFWS)" if not is_hindi else "आय < ₹8.00 लाख (TFWS)",
    "tfws_help": "Determines eligibility for the Tuition Fee Waiver Scheme (TFWS)." if not is_hindi else "ट्यूशन फीस माफी योजना (TFWS) के लिए पात्रता निर्धारित करता है।",
    "km_label": "Kashmiri Migrant (KM)" if not is_hindi else "कश्मीरी प्रवासी (KM)",
    "km_help": "5% additional supernumerary seats. Enforces Unreserved (GEN) base category." if not is_hindi else "5% अतिरिक्त अधिसंख्य सीटें। अनारक्षित (GEN) मूल श्रेणी लागू करता है।",
    "exs_label": "Ex-Servicemen (EXS)" if not is_hindi else "भूतपूर्व सैनिक (EXS)",
    "sports_label": "Valid Sports Quota" if not is_hindi else "वैध खेल कोटा (Sports Quota)",
    "sports_cat_label": "Sports Category" if not is_hindi else "खेल श्रेणी (Sports Category)",
    "widow_label": "Widow / Divorced (10%)" if not is_hindi else "विधवा / तलाकशुदा (10%)",
    "single_woman_label": "Single Woman Dependent (10%)" if not is_hindi else "एकल महिला के आश्रित (10%)",

    # UI Text
    "submit_btn": "🚀 Run DAP Eligibility Simulator" if not is_hindi else "🚀 डैप पात्रता सिम्युलेटर चलाएं",
    "toast_done": "Eligibility Calculation Completed!" if not is_hindi else "पात्रता गणना पूरी हुई!",
    "dashboard_title": "📊 Candidate Eligibility Dashboard" if not is_hindi else "📊 अभ्यर्थी पात्रता डैशबोर्ड",

    "disq_cutoff": "### ❌ Disqualified: Failed Minimum Eligibility" if not is_hindi else "### ❌ अपात्र: न्यूनतम पात्रता विफल",
    "require_marks": "Candidate requires at least 35%." if not is_hindi else "अभ्यर्थी को कम से कम 35% की आवश्यकता है।",
    "disq_aicte": "### ❌ Disqualified: Invalid Subject Group\n12th Lateral Entry requires at least Physics plus Mathematics or Chemistry." if not is_hindi else "### ❌ अपात्र: अमान्य विषय समूह\n12वीं लेटरल एंट्री के लिए कम से कम भौतिक विज्ञान के साथ गणित या रसायन विज्ञान की आवश्यकता है।",

    "priority_metric": "State Merit Priority Tier" if not is_hindi else "राज्य मेरिट प्राथमिकता स्तर",
    "matrix_metric": "Final Matrix Category" if not is_hindi else "अंतिम मैट्रिक्स श्रेणी",
    "outofstate_delta": "Quota Override Applied" if not is_hindi else "कोटा ओवरराइड लागू",

    "p1_granted": "Priority 1: State Eligible" if not is_hindi else "प्राथमिकता 1: राज्य पात्र",
    "p2_granted": "Priority 2: Out-of-State / UR" if not is_hindi else "प्राथमिकता 2: आउट-ऑफ-स्टेट / UR",
    "p2_warning": "⚠️ **Priority 2 Triggered:** Candidate does not meet Rajasthan priority conditions. Placed at the bottom of the merit list as Unreserved (GEN). All state reservations nullified." if not is_hindi else "⚠️ **प्राथमिकता 2 लागू:** अभ्यर्थी राजस्थान प्राथमिकता शर्तों को पूरा नहीं करता है। योग्यता सूची के अंत में अनारक्षित (GEN) के रूप में रखा गया। सभी आरक्षण निरस्त।",

    "fn_exclusive_error": "🛑 **FOREIGN NATIONAL / OCI / GULF POOL**\n\nCandidate is placed exclusively in the Foreign National list (`dap_fn`). No state vertical or horizontal reservations apply." if not is_hindi else "🛑 **विदेशी नागरिक / OCI / खाड़ी देश विशेष पूल**\n\nअभ्यर्थी को विशेष रूप से विदेशी नागरिक सूची (`dap_fn`) में रखा जाता है। कोई राज्य आरक्षण लागू नहीं होता है।",

    "group_eligible_msg": "Based on qualifications, eligible for branches:" if not is_hindi else "योग्यताओं के आधार पर, इन शाखाओं के लिए पात्र:",
    "all_branches": "ALL Diploma Branches" if not is_hindi else "सभी डिप्लोमा शाखाएं",

    "projected_lists_title": "🏆 Projected Ranking Lists" if not is_hindi else "🏆 अनुमानित रैंकिंग सूचियां",
    "tiebreaker_seq_msg": "Candidate will be positioned in the following sequence pools:" if not is_hindi else "उम्मीदवार को निम्नलिखित अनुक्रमों (पूल) में स्थान दिया जाएगा:",
    "eff_academic_score": "Effective Academic Score" if not is_hindi else "प्रभावी शैक्षणिक अंक",
    "based_on_10th": "(Based on 10th Board)" if not is_hindi else "(10वीं बोर्ड पर आधारित)",
    "based_on_diploma": "(Based on Diploma)" if not is_hindi else "(डिप्लोमा पर आधारित)",
    "based_on_cvoc": "(Based on 1 Yr C.Voc)" if not is_hindi else "(1 वर्ष C.Voc पर आधारित)",
    "based_on_iti": "(Based on 2 Yr ITI)" if not is_hindi else "(2 वर्ष ITI पर आधारित)",
    "based_on_12th": "(Based on 12th Board)" if not is_hindi else "(12वीं बोर्ड पर आधारित)",
    "pure_academic_caption": "Score based purely on qualifying examination." if not is_hindi else "विशुद्ध रूप से अर्हक परीक्षा पर आधारित स्कोर।",
    "download_report_btn": "📥 Download Official DAP Report (PDF)" if not is_hindi else "📥 आधिकारिक डैप रिपोर्ट डाउनलोड करें (PDF)",
    "pdf_install_helper": "💡 To enable PDF downloads, install: `pip install fpdf2`" if not is_hindi else "💡 PDF डाउनलोड के लिए इंस्टॉल करें: `pip install fpdf2`"
}

# --- 3. DROP DOWN OPTIONS & BILINGUAL MAPS ---
adm_options_en = ["Engineering Diploma (1st Year)", "Non-Engineering Diploma (1st Year)", "Lateral Entry (2nd Year Engineering)"]
adm_options = adm_options_en if not is_hindi else ["इंजीनियरिंग डिप्लोमा (प्रथम वर्ष)", "नॉन-इंजीनियरिंग डिप्लोमा (प्रथम वर्ष)", "लेटरल एंट्री (द्वितीय वर्ष इंजीनियरिंग)"]

gender_options = ["M", "F", "Other"] if not is_hindi else ["M (पुरुष)", "F (महिला)", "Other (अन्य)"]
gender_map = {"M": "M", "M (पुरुष)": "M", "F": "F", "F (महिला)": "F", "Other": "Other", "Other (अन्य)": "Other"}

category_options = ["GEN", "OBC (Non-Creamy)", "SC", "ST", "MBC (Non-Creamy)", "EWS"] if not is_hindi else ["GEN (सामान्य)", "OBC (नॉन-क्रीमी लेयर)", "SC (अनुसूचित जाति)", "ST (अनुसूचित जनजाति)", "MBC (नॉन-क्रीमी लेयर)", "EWS (कमजोर वर्ग)"]
category_map = {"GEN": "GEN", "GEN (सामान्य)": "GEN", "OBC (Non-Creamy)": "OBC (Non-Creamy)", "OBC (नॉन-क्रीमी लेयर)": "OBC (Non-Creamy)", "SC": "SC", "SC (अनुसूचित जाति)": "SC", "ST": "ST", "ST (अनुसूचित जनजाति)": "ST", "MBC (Non-Creamy)": "MBC (Non-Creamy)", "MBC (नॉन-क्रीमी लेयर)": "MBC (Non-Creamy)", "EWS": "EWS", "EWS (कमजोर वर्ग)": "EWS"}

area_options = ["Non-TSP", "TSP"] if not is_hindi else ["गैर-टीएसपी (Non-TSP)", "टीएसपी (TSP)"]
area_map = {"Non-TSP": "Non-TSP", "गैर-टीएसपी (Non-TSP)": "Non-TSP", "TSP": "TSP", "टीएसपी (TSP)": "TSP"}

domicile_options = ["Rajasthan", "Outside Rajasthan"] if not is_hindi else ["राजस्थान (Rajasthan)", "राजस्थान से बाहर (Outside Rajasthan)"]
domicile_map = {"Rajasthan": "Rajasthan", "राजस्थान (Rajasthan)": "Rajasthan", "Outside Rajasthan": "Outside Rajasthan", "राजस्थान से बाहर (Outside Rajasthan)": "Outside Rajasthan"}

exs_options = ["None", "EXS1 (Killed in action)", "EXS2 (Disabled in action)", "EXS3 (Died in service)", "EXS4 (Disabled in service)", "EXS5 (Gallantry Awards)", "EXS6 (Wards of EXS)", "EXS7 (Wives of EXS)", "EXS8 (Wards of Serving)", "EXS9 (Wives of Serving)"]
sports_cat_options = ["None", "A (Absolute Priority)", "B", "C", "D", "E"]

subject_list_en = ["Mathematics", "Chemistry", "Computer Science", "Electronics", "Information Technology", "Biology", "Informatics Practices", "Biotechnology", "Technical Vocational subject", "Agriculture", "Engineering Graphics", "Business Studies", "Entrepreneurship"]

# --- 4. OFFICIAL LOGO & NAVY BLUE HEADER STYLING ---
def get_base64_of_bin_file(bin_file):
    if os.path.exists(bin_file):
        with open(bin_file, 'rb') as f: return base64.b64encode(f.read()).decode()
    return ""

logo_base64 = get_base64_of_bin_file("CEGLogo.png")
logo_html = f'<img src="data:image/png;base64,{logo_base64}" class="header-logo">' if logo_base64 else ''

st.markdown(f"""
<style>
    .official-header {{ background: linear-gradient(135deg, #FFFFFF 0%, #F0F4F8 100%); padding: 20px 30px; border-radius: 12px; border-bottom: 4px solid {navy_blue}; border-top: 1px solid #E5E7EB; border-left: 1px solid #E5E7EB; border-right: 1px solid #E5E7EB; display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }}
    .header-text {{ display: flex; flex-direction: column; justify-content: center; }}
    .header-text h1 {{ font-family: 'Georgia', serif; font-weight: 800; margin: 0; margin-bottom: 5px; font-size: 2.6rem; color: {navy_blue} !important; line-height: 1.1; }}
    .header-text p {{ margin: 0; font-size: 1.1rem; letter-spacing: 1px; color: #4B5563 !important; font-weight: 600; }}
    .highlight {{ color: #D4AF37 !important; }}
    .header-logo {{ height: 100px; width: 100px; border-radius: 50%; object-fit: contain; }}
    div[data-baseweb="select"] > div:hover {{ border-color: {navy_blue} !important; }}
    .stTextInput input:focus, .stNumberInput input:focus, .stDateInput input:focus {{ border-color: {navy_blue} !important; box-shadow: 0 0 0 1px {navy_blue} !important; }}
    .stButton > button {{ background-color: {navy_blue} !important; color: #FFFFFF !important; border: none !important; transition: 0.2s; }}
    .stButton > button:hover {{ background-color: {navy_hover} !important; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.2); }}
    div[data-baseweb="checkbox"] input:checked + div {{ background-color: {navy_blue} !important; border-color: {navy_blue} !important; }}
    div[data-testid="stExpander"] {{ border-left: 4px solid {navy_blue} !important; }}
</style>
<div class="official-header"><div class="header-text"><h1>{T["app_title"]} <span class="highlight">2026</span></h1><p>{T["app_subtitle"]}</p></div>{logo_html}</div>
""", unsafe_allow_html=True)

# Custom Dashboard Card Component
def custom_metric(label, value, delta=None):
    delta_html = f"<div style='color: #4B5563; font-size: 1.05rem; margin-top: 8px; font-weight: 500;'>{delta}</div>" if delta else ""
    return f"""
    <div style="background-color: #FFFFFF; padding: 20px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); border-top: 5px solid {navy_blue}; margin-bottom: 15px; border: 1px solid #E5E7EB;">
        <div style="font-size: 1.1rem; color: #6B7280; font-weight: 600; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;">{label}</div>
        <div style="font-size: 2.2rem; color: {navy_blue}; font-weight: 700; line-height: 1.2; word-wrap: break-word; white-space: pre-wrap;">{value}</div>
        {delta_html}
    </div>
    """

# DISCLAIMER ADDED HERE
st.warning(f"**{T['disclaimer_title']}** {T['disclaimer_text']}")

# --- 5. PDF GENERATION ENGINE ---
def generate_pdf_report(data):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    navy, dark_gray, light_gray = (30, 58, 138), (55, 65, 81), (243, 244, 246)

    def clean_pdf_text(t):
        raw = str(t).replace('✅', '').replace('🔹', '').replace('🛑', '').replace('⚠️', '').replace('✨', '').replace('🏅', '').strip()
        return raw.encode('latin-1', 'replace').decode('latin-1')

    pdf.set_fill_color(*navy)
    pdf.rect(0, 0, 210, 42, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 24)
    pdf.set_y(10)
    pdf.cell(0, 10, 'DAP 2026', ln=True, align='C')
    pdf.set_text_color(212, 175, 55)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 6, 'DIPLOMA ADMISSION PROCESS - ELIGIBILITY REPORT', ln=True, align='C')
    pdf.ln(22)

    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 15)
    pdf.cell(0, 10, 'TENTATIVE EVALUATION SUMMARY', ln=True)
    pdf.set_draw_color(*navy)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    pdf.set_text_color(*dark_gray)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(95, 7, 'CANDIDATE PROFILE', ln=False)
    pdf.cell(95, 7, 'ACADEMIC CREDENTIALS', ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Name:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, clean_pdf_text(data.get('name')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Admission Type:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, clean_pdf_text(data.get('adm_type')), ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Date of Birth:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, str(data.get('dob')), ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Qualifying Exam:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, clean_pdf_text(data.get('qual_exam')), ln=True)

    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Category & Gen:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(50, 6, f"{clean_pdf_text(data.get('category'))} ({clean_pdf_text(data.get('gender'))})", ln=False)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(35, 6, 'Effective Score:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(70, 6, f"{data.get('entered_perc', 0.0):.2f}", ln=True)
    pdf.ln(8)

    box_start_y = pdf.get_y()
    pdf.set_fill_color(*light_gray)
    pdf.rect(10, box_start_y, 190, 35, 'F')
    pdf.set_y(box_start_y + 3)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(*navy)
    pdf.cell(0, 7, '   SIMULATION EVALUATION RESULTS', ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(*dark_gray)
    pdf.cell(60, 6, '     State Merit Priority Tier:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, clean_pdf_text(data.get('display_priority')), ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Final Seat Matrix Category:', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, clean_pdf_text(data.get('backend_category')), ln=True)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(60, 6, '     Eligible AICTE Group(s):', ln=False)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(130, 6, ', '.join([clean_pdf_text(g) for g in data.get('eligible_groups')]), ln=True)

    pdf.set_y(box_start_y + 40)
    pdf.set_text_color(*navy)
    pdf.set_font('Helvetica', 'B', 13)
    pdf.cell(0, 8, 'PROJECTED TARGET RANKING COHORTS', ln=True)
    pdf.set_draw_color(*navy)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(*dark_gray)
    for rank in data.get('ranks', []):
        pdf.cell(0, 6, f"- {clean_pdf_text(rank)}", ln=True)

    pdf.ln(6)
    pdf.set_fill_color(254, 243, 199)
    pdf.set_text_color(180, 83, 9)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.cell(0, 6, 'OFFICIAL DAP-2026 SYSTEM DISCLAIMER:', ln=True, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 7.5)
    disclaimer = "This Eligibility Simulator is provided for informational and guidance purposes only. The projected priority tiers, effective scores, and ranking lists generated by this tool are tentative and based entirely on the unverified data entered by the candidate. The final, official merit list and ranks will be generated by the Centre for Electronic Governance (CEG) during the actual DAP-2026 Centralized Admission Process after thorough verification of original documents."
    pdf.multi_cell(0, 4, disclaimer, align='L', fill=True)

    return bytes(pdf.output())

# --- 6. INPUT LAYOUT (Dynamic & Reactive) ---
st.markdown(f"### {T['eval_details_header']}")

with st.expander(T["step1_title"], expanded=True):
    c1, c2, c3 = st.columns(3)
    with c1:
        name = st.text_input(T["cand_name"], "")
    with c2:
        dob = st.date_input(T["dob"], value=datetime(2005, 1, 1), min_value=datetime(1970, 1, 1), max_value=datetime.today(), help=T["dob_help"])
    with c3:
        sel_adm_type = st.selectbox(T["adm_type"], adm_options)

    st.markdown("---")
    adm_idx = adm_options.index(sel_adm_type)
    sel_adm_type_en = adm_options_en[adm_idx]
    is_lateral = "Lateral Entry" in sel_adm_type_en

    if sel_adm_type_en == "Engineering Diploma (1st Year)":
        qual_opts_en = ["10th Board"]
        qual_opts = ["10th Board"] if not is_hindi else ["10वीं बोर्ड"]
    elif sel_adm_type_en == "Non-Engineering Diploma (1st Year)":
        qual_opts_en = ["Diploma (Non-Engineering)", "10th Board"]
        qual_opts = ["Diploma (Non-Engineering)", "10th Board"] if not is_hindi else ["डिप्लोमा (नॉन-इंजीनियरिंग)", "10वीं बोर्ड"]
    else:
        qual_opts_en = ["Diploma (Engineering)", "10th + 1 Yr C.Voc", "10th + 2 Yr ITI", "12th Board"]
        qual_opts = qual_opts_en if not is_hindi else ["डिप्लोमा (इंजीनियरिंग)", "10वीं + 1 वर्ष C.Voc", "10वीं + 2 वर्ष ITI", "12वीं बोर्ड"]

    c4, c5 = st.columns(2)
    with c4:
        qual_exam = st.selectbox(T["qual_basis"], qual_opts)
        qual_exam_en = qual_opts_en[qual_opts.index(qual_exam)]

    entered_perc = 0.0
    selected_subs = []
    with c5:
        entered_perc = st.number_input(T["perc_qual"], min_value=0.0, max_value=100.0, value=75.0, step=0.1, help=T["cutoff_help"])

    if is_lateral and "12" in qual_exam_en:
        st.markdown(f"##### {T['subject_12_title']}")
        st.caption(T["subject_12_caption"])
        c_s1, c_s2, c_s3 = st.columns(3)
        selected_sub1 = c_s1.selectbox(T["sub1_label"], ["Physics"], disabled=True)
        sub2_options = ["-- Select --"] + subject_list_en
        selected_sub2 = c_s2.selectbox(T["sub2_label"], sub2_options)
        sub3_options = ["-- Select --"] + [s for s in subject_list_en if s != selected_sub2]
        selected_sub3 = c_s3.selectbox(T["sub3_label"], sub3_options, disabled=(selected_sub2 == "-- Select --"))
        selected_subs = ["Physics", selected_sub2, selected_sub3]

with st.expander(T["step2_title"], expanded=True):
    st.info(T["priority_help"])

    cp1, cp2, cp3 = st.columns(3)
    with cp1:
        sel_domicile = st.selectbox(T["domicile"], domicile_options)
        domicile = domicile_map[sel_domicile]
    with cp2:
        passed_raj = st.checkbox(T["passed_raj"], value=True)
    with cp3:
        govt_emp = st.checkbox(T["govt_emp"], value=False)

    cpl1, cpl2, cpl3 = st.columns(3)
    with cpl1:
        psu_emp = st.checkbox(T["psu_emp"], value=False)

    passed_bter, passed_iti_raj = False, False
    if is_lateral:
        with cpl2: passed_bter = st.checkbox(T["passed_bter"], value=False)
        with cpl3: passed_iti_raj = st.checkbox(T["passed_iti_raj"], value=False)

    st.markdown("---")

    # --- PROACTIVE LOCKOUT UX TRIGGER ---
    km_quota = st.checkbox(T["km_label"], help=T["km_help"])
    is_locked_out = (domicile != "Rajasthan" or km_quota)
    
    if is_locked_out:
        st.warning("⚠️ **Reservations Disabled:** Candidate is out-of-state or applying under Kashmiri Migrant quota." if not is_hindi else "⚠️ **आरक्षण अक्षम:** अभ्यर्थी आउट-ऑफ-स्टेट है या कश्मीरी प्रवासी कोटे के तहत आवेदन कर रहा है।")

    st.markdown("---")
    c7, c8 = st.columns(2)
    with c7:
        sel_gender = st.selectbox(T["gender"], gender_options, help=T["gender_help"])
        gender = gender_map[sel_gender]
    with c8:
        sel_category = st.selectbox(T["base_cat"], category_options, disabled=is_locked_out)
        category = category_map[sel_category]
        sel_area = st.selectbox(T["area"], area_options, disabled=is_locked_out)
        area = area_map[sel_area]

with st.expander(T["step3_title"], expanded=False):
    fn_quota = st.checkbox(T["fn_label"], help=T["fn_help"])
    st.markdown("---")

    c9, c10 = st.columns(2)
    with c9:
        pwd_quota = st.checkbox(T["pwd_label"], help=T["pwd_help"], disabled=(fn_quota or is_locked_out))
        income_less_8l = st.checkbox(T["tfws_label"], help=T["tfws_help"], disabled=fn_quota)
        
    with c10:
        sel_exs = st.selectbox(T["exs_label"], exs_options, disabled=(fn_quota or is_locked_out))
        exs_priority = sel_exs.split(" ")[0] if sel_exs != "None" and sel_exs != "कोई नहीं" else "None"
        
        sports_quota = st.checkbox(T["sports_label"], disabled=(fn_quota or is_locked_out))
        sel_sports_cat = st.selectbox(T["sports_cat_label"], sports_cat_options, disabled=(not sports_quota or fn_quota or is_locked_out))
        sports_cat = sel_sports_cat.split(" ")[0] if sel_sports_cat != "None" and sel_sports_cat != "कोई नहीं" else "None"

    widow_quota, single_woman_quota = False, False
    if gender in ["F", "Other", "F (महिला)", "Other (अन्य)"]:
        st.markdown("---")
        cf1, cf2 = st.columns(2)
        with cf1: widow_quota = st.checkbox(T["widow_label"], disabled=(fn_quota or is_locked_out))
        with cf2: single_woman_quota = st.checkbox(T["single_woman_label"], disabled=(widow_quota or fn_quota or is_locked_out))

st.markdown("<br>", unsafe_allow_html=True)
_, submit_btn_col2, _ = st.columns([1, 1, 1])
with submit_btn_col2:
    submitted = st.button(T["submit_btn"], use_container_width=True)

# --- 7. ALGORITHM EXECUTION & DASHBOARD ---
if submitted:
    st.toast(T["toast_done"], icon="✅")
    st.divider()
    st.markdown(f"## {T['dashboard_title']}")

    if is_lateral:
        is_priority_1 = (domicile == "Rajasthan") or passed_raj or govt_emp or psu_emp or passed_bter or passed_iti_raj
    else:
        is_priority_1 = (domicile == "Rajasthan") or passed_raj or govt_emp or psu_emp

    backend_category = category
    km_override_applied = False
    dom_override_applied = False

    # 1. Apply Kashmiri Migrant Category Wipe 
    if km_quota and not fn_quota:
        backend_category = "GEN"
        km_override_applied = True
        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False
        widow_quota = False
        single_woman_quota = False

    # 2. Apply Out-of-State Category Wipe
    if domicile != "Rajasthan" and not km_override_applied and not fn_quota:
        if backend_category != "GEN":
            backend_category = "GEN"
            dom_override_applied = True 
        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False
        widow_quota = False
        single_woman_quota = False

    # 3. Fallback for Priority 2
    if not is_priority_1 and not km_override_applied and not fn_quota:
        backend_category = "GEN"
        pwd_quota = False
        exs_priority = "None"
        area = "Non-TSP"
        sports_quota = False
        widow_quota = False
        single_woman_quota = False

    req_cutoff = 35.0
    is_eligible_marks = entered_perc >= req_cutoff
    eligible_groups = []

    if not is_eligible_marks:
        st.error(f"{T['disq_cutoff']}\n\n{T['require_marks']} Scored: {entered_perc}%.")
    else:
        # SPORTS BONUS ADDITION
        effective_score = float(entered_perc)
        sports_bonus_applied = False
        sports_weight = 0.0
        cat_letter = "None"
        sports_a_triggered = False

        if is_priority_1 and sports_quota and sports_cat != "None" and not fn_quota:
            cat_letter = sports_cat
            if cat_letter == "A":
                sports_weight = 7.0
                sports_a_triggered = True
            elif cat_letter == "B":
                sports_weight = 7.0
            elif cat_letter == "C":
                sports_weight = 5.0
            elif cat_letter == "D":
                sports_weight = 4.0
            elif cat_letter == "E":
                sports_weight = 2.0

            effective_score += sports_weight
            sports_bonus_applied = True

        # BRANCH ELIGIBILITY LOGIC
        if is_lateral and "12" in qual_exam_en:
            subs_set = set(selected_subs)
            if "-- Select --" in selected_subs:
                st.error(T["disq_aicte"])
                st.stop()

            has_math = "Mathematics" in subs_set
            has_chem = "Chemistry" in subs_set

            if has_math and has_chem:
                eligible_groups.append("All Engineering Diploma Branches (Mechanical, Civil, Chemical, etc.)")
            elif has_math:
                eligible_groups.append("CS, IT, Electrical, Electronics, Robotics, Fibre Optics")
            elif has_chem:
                eligible_groups.append("Printing Technology")
            else:
                st.error(T["disq_aicte"])
                st.stop()
        else:
            eligible_groups.append(T["all_branches"])

        st.success(f"✅ **{T['group_eligible_msg']}** {', '.join(eligible_groups)}")

        if is_lateral and "12" in qual_exam_en:
            with st.expander("📄 View Lateral Entry Qualification Matrix / लेटरल एंट्री योग्यता मैट्रिक्स देखें", expanded=False):
                st.markdown("""
                **Official 10+2 Qualification Matrix (Lateral Entry):**
                * **PCM (Physics, Chemistry, Maths):** Eligible for ALL Engineering Branches.
                * **Physics + Maths + Any other subject:** CS, IT, Electrical, Electronics, Robotics, Fibre Optics.
                * **Physics + Chemistry + Any other subject:** Printing Technology.
                """)
                pdf_filename = "Lateral Qualification Matrix.pdf"
                if os.path.exists(pdf_filename):
                    with open(pdf_filename, "rb") as pdf_file:
                        pdf_b64 = base64.b64encode(pdf_file.read()).decode()
                        st.markdown(f'''<a href="data:application/pdf;base64,{pdf_b64}" download="{pdf_filename}" style="display: block; padding: 0.6rem 1rem; color: #FFFFFF; background-color: {navy_blue}; border-radius: 6px; text-decoration: none; font-weight: 600; text-align: center; margin-top: 10px;">📥 Download Detailed 10+2 Qualification Matrix</a>''', unsafe_allow_html=True)

        # MERIT TIER GENERATION
        if sel_adm_type_en == "Engineering Diploma (1st Year)":
            tier_str = "10th Board Merit"
            gauge_suffix = T["based_on_10th"]
        elif sel_adm_type_en == "Non-Engineering Diploma (1st Year)":
            if "Diploma" in qual_exam_en:
                tier_str = "Non-Engg Tier 1: Diploma"
                gauge_suffix = "(Based on Diploma)" if not is_hindi else "(डिप्लोमा पर आधारित)"
            else:
                tier_str = "Non-Engg Tier 2: 10th Board"
                gauge_suffix = T["based_on_10th"]
        else:
            if "Diploma" in qual_exam_en:
                tier_str = "Lateral Tier 1: Diploma"
                gauge_suffix = T["based_on_diploma"]
            elif "C.Voc" in qual_exam_en:
                tier_str = "Lateral Tier 2: 1 Yr C.Voc"
                gauge_suffix = T["based_on_cvoc"]
            elif "ITI" in qual_exam_en:
                tier_str = "Lateral Tier 3: 2 Yr ITI"
                gauge_suffix = T["based_on_iti"]
            else:
                tier_str = "Lateral Tier 4: 12th Board"
                gauge_suffix = T["based_on_12th"]

        p_text = T["p1_granted"] if is_priority_1 else T["p2_granted"]
        
        # --- UI OVERRIDE FOR SPORTS A ---
        base_display_priority = f"{tier_str} | ({p_text})"
        if sports_a_triggered:
            display_priority = "Priority: Sports A" if not is_hindi else "प्राथमिकता: Sports A"
        else:
            display_priority = base_display_priority

        dash_col1, dash_col2 = st.columns([1.5, 1])

        with dash_col1:
            c_m1, c_m2 = st.columns(2)
            with c_m1:
                st.markdown(custom_metric(T["priority_metric"], display_priority), unsafe_allow_html=True)
            with c_m2:
                delta_val = T["outofstate_delta"] if (dom_override_applied or km_override_applied) and not fn_quota else None
                st.markdown(custom_metric(T["matrix_metric"], backend_category, delta_val), unsafe_allow_html=True)

            # Warning Management
            if not is_priority_1 and not km_override_applied and not fn_quota:
                st.warning(T["p2_warning"])
            elif km_override_applied:
                km_warning = "⚠️ **Kashmiri Migrant Rule Applied:** Vertical and horizontal reservations are nullified. Eligible for Unreserved (GEN) State Merit and supernumerary KM seats." if not is_hindi else "⚠️ **कश्मीरी प्रवासी नियम लागू:** ऊर्ध्वाधर और क्षैतिज आरक्षण निरस्त कर दिए गए हैं। अनारक्षित (GEN) राज्य मेरिट और अधिसंख्य KM सीटों के लिए पात्र।"
                st.warning(km_warning)
            elif domicile != "Rajasthan" and is_priority_1 and not fn_quota:
                out_of_state_warning = "⚠️ **Out-of-State Rule Applied:** Candidate has Priority 1 status but is not a domicile of Rajasthan. Vertical and horizontal reservations are nullified. Eligible for Unreserved (GEN) State Merit only." if not is_hindi else "⚠️ **आउट-ऑफ-स्टेट नियम लागू:** अभ्यर्थी को प्राथमिकता 1 का दर्जा प्राप्त है लेकिन वह राजस्थान का मूल निवासी नहीं है। ऊर्ध्वाधर और क्षैतिज आरक्षण निरस्त कर दिए गए हैं। केवल अनारक्षित (GEN) राज्य मेरिट के लिए पात्र।"
                st.warning(out_of_state_warning)

            # Sports A Dynamic Fallback Warning
            if sports_a_triggered:
                sports_a_msg_en = f"**Note:** Priority-Sports A is capped at 5% of total intake seats. If candidate does not secure a Sports A seat, he/she will fall back to **Priority: {tier_str}** with an Effective Academic Score of {effective_score:.2f}."
                sports_a_msg_hi = f"**नोट:** प्राथमिकता-Sports A कुल इन्टेक सीटों के 5% तक ही सीमित है। यदि अभ्यर्थी Sports A सीट प्राप्त नहीं कर पाता है, तो वह **Priority: {tier_str}** पर वापस आ जाएगा, जिसमें प्रभावी शैक्षणिक स्कोर {effective_score:.2f} होगा।"
                st.info(sports_a_msg_hi if is_hindi else sports_a_msg_en)

            st.markdown(f"### {T['projected_lists_title']}")

            if fn_quota:
                st.error(T["fn_exclusive_error"])
                ranks = ["🔹 `dap_fn` (Foreign National/OCI/Gulf Quota - 15% Supernumerary)"]
                st.success(T["tiebreaker_seq_msg"])
                st.info("\n".join(ranks))
            else:
                ranks = []
                if is_priority_1:
                    ranks.append("🔹 `dap_merit` (Overall State Diploma Merit)")
                    if gender in ["F", "F (महिला)"]: ranks.append("🔹 `dap_genf` (Overall General Female)")
                    if backend_category != "GEN":
                        clean_cat = backend_category.split(" ")[0].lower()
                        ranks.append(f"🔹 `dap_{clean_cat}` (Category {backend_category})")
                        if gender in ["F", "F (महिला)"]: ranks.append(f"🔹 `dap_{clean_cat}f` (Category {backend_category} Female)")
                    if backend_category == "ST" and area == "TSP":
                        ranks.append("🔹 `dap_tsp` (TSP Quota)")
                    if pwd_quota: ranks.append("🔹 `dap_pwd` (Persons with Special Ability - 5%)")
                    if exs_priority != "None": ranks.append(f"🔹 `dap_exs` (Ex-Servicemen - {exs_priority})")
                    if widow_quota: ranks.append("🔹 `dap_widow` (Widow/Divorced Quota - 10%)")
                    if single_woman_quota: ranks.append("🔹 `dap_singlew` (Single Woman Dependent Quota - 10%)")
                    
                    # Sports Ranks (with Fallback string for A)
                    if sports_quota and sports_cat != "None": 
                        if sports_a_triggered:
                            ranks.append("🔹 `dap_sports` (Priority: Sports A - Max 5% capacity, then falls back to Sports Category B)" if not is_hindi else "🔹 `dap_sports` (प्राथमिकता: Sports A - कुल सीटों के 5% तक सीमित, फिर Sports Category B पर वापस)")
                        else:
                            ranks.append(f"🔹 `dap_sports` (Sports Category {sports_cat})")
                else:
                    ranks.append("🔹 `dap_ur` (Priority 2 / Unreserved Quota)")

                if km_quota: ranks.append("🔹 `dap_km` (Kashmiri Migrant Supernumerary Quota - 5%)")
                if income_less_8l: ranks.append("🔹 `dap_tfw` (Tuition Fee Waiver Scheme - 5%)")

                st.success(T["tiebreaker_seq_msg"])
                st.info("\n".join(ranks))

            if FPDF_AVAILABLE:
                pdf_p_text = "Priority 1: State Eligible" if is_priority_1 else "Priority 2: Out-of-State / UR"
                
                # --- PDF REPORT OVERRIDE FOR SPORTS A ---
                pdf_base_priority = f"{tier_str} | ({pdf_p_text})"
                pdf_display_priority = "Priority: Sports A" if sports_a_triggered else pdf_base_priority
                
                pdf_eligible_groups = ["ALL Diploma Branches"] if eligible_groups[0] == T["all_branches"] else eligible_groups

                pdf_payload = {
                    'name': name if name.strip() else "Candidate",
                    'dob': dob.strftime('%d-%m-%Y'),
                    'adm_type': sel_adm_type_en,
                    'qual_exam': qual_exam_en,
                    'entered_perc': effective_score,
                    'category': backend_category,
                    'gender': gender_map[sel_gender],
                    'display_priority': pdf_display_priority,
                    'backend_category': backend_category,
                    'eligible_groups': pdf_eligible_groups,
                    'ranks': ranks
                }
                try:
                    pdf_data = generate_pdf_report(pdf_payload)
                    st.download_button(label=T["download_report_btn"], data=pdf_data, file_name=f"DAP_2026_Report.pdf", mime="application/pdf", use_container_width=True)
                except Exception as e:
                    st.error(f"Error compiling PDF: {e}")
            else:
                st.info(T["pdf_install_helper"])

        with dash_col2:
            gauge_full_title = f"{T['eff_academic_score']}<br><span style='font-size:14px;color:#6B7280'>{gauge_suffix}</span>"
            fig = go.Figure(go.Indicator(
                mode="gauge+number+delta" if sports_bonus_applied else "gauge+number",
                value=effective_score,
                delta={'reference': float(entered_perc), 'position': "top", 'valueformat': '.2f'} if sports_bonus_applied else None,
                domain={'x': [0, 1], 'y': [0, 1]},
                title={'text': gauge_full_title, 'font': {'size': 22, 'color': theme_axis_color}},
                number={'font': {'color': theme_axis_color}, 'valueformat': '.2f'},
                gauge={
                    'axis': {'range': [None, 110], 'tickwidth': 1, 'tickcolor': theme_axis_color, 'tickfont': {'color': theme_axis_color}},
                    'bar': {'color': navy_blue, 'thickness': 0.75},
                    'bgcolor': "rgba(0,0,0,0)",
                    'borderwidth': 2,
                    'bordercolor': "gray",
                    'steps': [
                        {'range': [0, req_cutoff], 'color': "rgba(239, 68, 68, 0.4)"},
                        {'range': [req_cutoff, 65], 'color': "rgba(191, 219, 254, 0.5)"},
                        {'range': [65, 110], 'color': "rgba(30, 58, 138, 0.3)"}],
                    'threshold': {'line': {'color': "#EF4444", 'width': 4}, 'thickness': 1, 'value': req_cutoff}
                }
            ))

            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)", height=350, margin=dict(l=20, r=20, t=110, b=20), font=dict(color=theme_axis_color))
            st.plotly_chart(fig, use_container_width=True, theme=chart_theme)

            if sports_bonus_applied:
                sports_bonus_caption_en = f"✨ Score includes **+{sports_weight} points** for Sports Category {cat_letter}."
                sports_bonus_caption_hi = f"✨ स्कोर में स्पोर्ट्स श्रेणी {cat_letter} के लिए **+{sports_weight} अंक** शामिल हैं।"
                st.caption(sports_bonus_caption_hi if is_hindi else sports_bonus_caption_en)
            else:
                st.caption(T["pure_academic_caption"])
